/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellPatientsRouteImport } from './routes/_shell.patients'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellPatientsIndexRouteImport } from './routes/_shell.patients.index'
import { Route as ShellPatientsNewRouteImport } from './routes/_shell.patients.new'
import { Route as ShellPatientsPatientIdRouteImport } from './routes/_shell.patients.$patientId'
import { Route as ShellPatientsPatientIdIndexRouteImport } from './routes/_shell.patients.$patientId.index'
import { Route as ShellPatientsPatientIdEditRouteImport } from './routes/_shell.patients.$patientId.edit'
import { Route as ShellPatientsPatientIdConsultationsRouteImport } from './routes/_shell.patients.$patientId.consultations'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsRoute = ShellPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatientsIndexRoute = ShellPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellPatientsRoute,
} as any)
const ShellPatientsNewRoute = ShellPatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellPatientsRoute,
} as any)
const ShellPatientsPatientIdRoute = ShellPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => ShellPatientsRoute,
} as any)
const ShellPatientsPatientIdIndexRoute =
  ShellPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellPatientsPatientIdRoute,
  } as any)
const ShellPatientsPatientIdEditRoute =
  ShellPatientsPatientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ShellPatientsPatientIdRoute,
  } as any)
const ShellPatientsPatientIdConsultationsRoute =
  ShellPatientsPatientIdConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => ShellPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof ShellDashboardRoute
  '/patients': typeof ShellPatientsRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/patients/$patientId': typeof ShellPatientsPatientIdRouteWithChildren
  '/patients/new': typeof ShellPatientsNewRoute
  '/patients/': typeof ShellPatientsIndexRoute
  '/patients/$patientId/consultations': typeof ShellPatientsPatientIdConsultationsRoute
  '/patients/$patientId/edit': typeof ShellPatientsPatientIdEditRoute
  '/patients/$patientId/': typeof ShellPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof ShellDashboardRoute
  '/settings': typeof ShellSettingsRoute
  '/patients/new': typeof ShellPatientsNewRoute
  '/patients': typeof ShellPatientsIndexRoute
  '/patients/$patientId/consultations': typeof ShellPatientsPatientIdConsultationsRoute
  '/patients/$patientId/edit': typeof ShellPatientsPatientIdEditRoute
  '/patients/$patientId': typeof ShellPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/patients': typeof ShellPatientsRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/patients/$patientId': typeof ShellPatientsPatientIdRouteWithChildren
  '/_shell/patients/new': typeof ShellPatientsNewRoute
  '/_shell/patients/': typeof ShellPatientsIndexRoute
  '/_shell/patients/$patientId/consultations': typeof ShellPatientsPatientIdConsultationsRoute
  '/_shell/patients/$patientId/edit': typeof ShellPatientsPatientIdEditRoute
  '/_shell/patients/$patientId/': typeof ShellPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/patients'
    | '/settings'
    | '/patients/$patientId'
    | '/patients/new'
    | '/patients/'
    | '/patients/$patientId/consultations'
    | '/patients/$patientId/edit'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/patients/new'
    | '/patients'
    | '/patients/$patientId/consultations'
    | '/patients/$patientId/edit'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/_shell/dashboard'
    | '/_shell/patients'
    | '/_shell/settings'
    | '/_shell/patients/$patientId'
    | '/_shell/patients/new'
    | '/_shell/patients/'
    | '/_shell/patients/$patientId/consultations'
    | '/_shell/patients/$patientId/edit'
    | '/_shell/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients': {
      id: '/_shell/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ShellPatientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/patients/': {
      id: '/_shell/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof ShellPatientsIndexRouteImport
      parentRoute: typeof ShellPatientsRoute
    }
    '/_shell/patients/new': {
      id: '/_shell/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof ShellPatientsNewRouteImport
      parentRoute: typeof ShellPatientsRoute
    }
    '/_shell/patients/$patientId': {
      id: '/_shell/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof ShellPatientsPatientIdRouteImport
      parentRoute: typeof ShellPatientsRoute
    }
    '/_shell/patients/$patientId/': {
      id: '/_shell/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof ShellPatientsPatientIdIndexRouteImport
      parentRoute: typeof ShellPatientsPatientIdRoute
    }
    '/_shell/patients/$patientId/edit': {
      id: '/_shell/patients/$patientId/edit'
      path: '/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof ShellPatientsPatientIdEditRouteImport
      parentRoute: typeof ShellPatientsPatientIdRoute
    }
    '/_shell/patients/$patientId/consultations': {
      id: '/_shell/patients/$patientId/consultations'
      path: '/consultations'
      fullPath: '/patients/$patientId/consultations'
      preLoaderRoute: typeof ShellPatientsPatientIdConsultationsRouteImport
      parentRoute: typeof ShellPatientsPatientIdRoute
    }
  }
}

interface ShellPatientsPatientIdRouteChildren {
  ShellPatientsPatientIdConsultationsRoute: typeof ShellPatientsPatientIdConsultationsRoute
  ShellPatientsPatientIdEditRoute: typeof ShellPatientsPatientIdEditRoute
  ShellPatientsPatientIdIndexRoute: typeof ShellPatientsPatientIdIndexRoute
}

const ShellPatientsPatientIdRouteChildren: ShellPatientsPatientIdRouteChildren =
  {
    ShellPatientsPatientIdConsultationsRoute:
      ShellPatientsPatientIdConsultationsRoute,
    ShellPatientsPatientIdEditRoute: ShellPatientsPatientIdEditRoute,
    ShellPatientsPatientIdIndexRoute: ShellPatientsPatientIdIndexRoute,
  }

const ShellPatientsPatientIdRouteWithChildren =
  ShellPatientsPatientIdRoute._addFileChildren(
    ShellPatientsPatientIdRouteChildren,
  )

interface ShellPatientsRouteChildren {
  ShellPatientsPatientIdRoute: typeof ShellPatientsPatientIdRouteWithChildren
  ShellPatientsNewRoute: typeof ShellPatientsNewRoute
  ShellPatientsIndexRoute: typeof ShellPatientsIndexRoute
}

const ShellPatientsRouteChildren: ShellPatientsRouteChildren = {
  ShellPatientsPatientIdRoute: ShellPatientsPatientIdRouteWithChildren,
  ShellPatientsNewRoute: ShellPatientsNewRoute,
  ShellPatientsIndexRoute: ShellPatientsIndexRoute,
}

const ShellPatientsRouteWithChildren = ShellPatientsRoute._addFileChildren(
  ShellPatientsRouteChildren,
)

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellPatientsRoute: typeof ShellPatientsRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellPatientsRoute: ShellPatientsRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
